apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-db
type: Opaque
stringData:
  database.properties: |-
    connectionProperties.user={{.Values.server.db.user}}
    connectionProperties.password={{.Values.server.db.password}}
    connectionUrl=jdbc\:mysql\://{{.Values.server.db.host}}/{{.Values.server.db.name}}
