{{ if .Values.server.logging.enabled }}
apiVersion: v1
data:
  fluent-bit.conf: |-
    [INPUT]
        Name             tail
        Path             /opt/teamcity/logs/teamcity-server.log

    [INPUT]
        Name             tail
        Path             /opt/teamcity/logs/teamcity-auth.log

    [OUTPUT]
        Name  stdout
        Match *
kind: ConfigMap
metadata:
  name: server-fluentbit
  namespace: {{.Release.Namespace}}
{{ end }}
