{{ if .Values.agent.logging.enabled }}
apiVersion: v1
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush         1

    [INPUT]
        Name             tail
        Path             /opt/buildagent/logs/teamcity-agent.log
        Mem_Buf_Limit    5MB

    [INPUT]
        Name             tail
        Path             /opt/buildagent/logs/error.log
        Mem_Buf_Limit     5MB

    [OUTPUT]
        Name  stdout
        Match *
kind: ConfigMap
metadata:
  name: agent-fluentbit
  namespace: {{.Release.Namespace}}
{{ end }}
