apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teamcity.fullname" . }}
  namespace: {{.Release.Namespace}}
data:
  database.properties: |-
    connectionProperties.user={{.Values.server.db.user}}
    connectionProperties.password={{.Values.server.db.password}}
    connectionUrl=jdbc\:mysql\://{{.Values.server.db.host}}/{{.Values.server.db.name}}
  download_plugins.sh: |-
    {{- if .Values.server.plugins }}
    {{- range $key, $val := .Values.server.plugins }}
    wget -c {{ $val }} -O /plugins/{{ $key }}
    {{- end }}
    {{- end }}
  internal.properties: |-
  {{- if .Values.server.internal_properties }}
  {{- range $key, $val := .Values.server.internal_properties }}
      {{ $key }}={{ $val }}
    {{- end }}
    {{- end }}