apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamcity.fullname" . }}-server
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teamcity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "teamcity.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.server.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      initContainers:
        - name: download-plugins
          image: alpine:latest
          command:
            - "sh"
            - "/download_plugins.sh"
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: config
              mountPath: /download_plugins.sh
              subPath: download_plugins.sh
        - name: volume-hack
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - chown -v -R 1000:1000 /mount;
          volumeMounts:
          - name: data
            mountPath: /mount
      containers:
      {{ if .Values.server.logging.enabled }}
        - name: fluentbit
          image: fluent/fluent-bit:1.0.6
          volumeMounts:
          - name: logs
            mountPath: /opt/teamcity/logs
          - name: fluentbit-config
            mountPath: /fluent-bit/etc/fluent-bit.conf
            subPath: fluent-bit.conf
      {{ end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8111
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /mnt/get/stateRevision
              port: 8111
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /mnt/get/stateRevision
              port: 8111
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
          - name: config
            mountPath: /data/teamcity_server/datadir/config/database.properties
            subPath: database.properties
            readOnly: true
          - name: plugins
            mountPath: /data/teamcity_server/datadir/plugins
            readOnly: false
          - name: data
            mountPath: /data/teamcity_server/datadir
        {{ if .Values.server.logging.enabled }}
          - name: logs
            mountPath: /opt/teamcity/logs
        {{ end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
      {{ if .Values.server.logging.enabled }}
      - name: fluentbit-config
        configMap:
          name: server-fluentbit
      - name: logs
        emptyDir: {}
      {{ end }}
      - name: plugins
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "teamcity.fullname" . }}-server-data
      - name: config
        configMap:
          name: {{ include "teamcity.fullname" . }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
