{{- if .Values.server.persistentDataDir.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcity.fullname" . }}-server-data
spec:
  storageClassName: {{.Values.server.persistentDataDir.storageClass}}
  accessModes: {{.Values.server.persistentDataDir.accessModes}}
  resources:
    requests:
      storage: {{.Values.server.persistentDataDir.size}}
{{- end }}
