apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8111
      protocol: TCP
      name: http
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}
